apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-demo-app-deployment
  labels:
    app: db-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-demo-app
  template:
    metadata:
      labels:
        app: db-demo-app
    spec:
      containers:
        - image: mongo
          name: db-demo-app
          ports:
            - containerPort: 27017
      restartPolicy: Always
